#!/usr/bin/env node
/**
 * build-data.js
 *
 * Compiles YAML data files from /data/ into a single ES module at src/data.js
 * that the React app imports. This keeps the runtime bundle lean while allowing
 * non-coder contributors to edit YAML directly.
 *
 * Usage: npm run build:data
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const CARDS_DIR = path.join(ROOT, 'data', 'cards');
const PARTNERS_DIR = path.join(ROOT, 'data', 'partners');
const SOURCES_FILE = path.join(ROOT, 'data', 'sources', 'registry.yaml');
const OUTPUT = path.join(ROOT, 'src', 'data.js');

function loadYamlDir(dir) {
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.yaml') && !f.startsWith('_'))
    .map(f => {
      const raw = fs.readFileSync(path.join(dir, f), 'utf8');
      try {
        return yaml.load(raw);
      } catch (err) {
        console.error(`YAML parse error in ${f}:`, err.message);
        process.exit(1);
      }
    });
}

function main() {
  console.log('Building data...');

  const cards = loadYamlDir(CARDS_DIR);
  const partners = loadYamlDir(PARTNERS_DIR);
  const sourcesRaw = yaml.load(fs.readFileSync(SOURCES_FILE, 'utf8'));
  const sources = sourcesRaw.sources;

  console.log(`  ${cards.length} cards`);
  console.log(`  ${partners.length} partners`);
  console.log(`  ${sources.length} data sources`);

  // Build the SOURCE_PROGRAMS object keyed by id
  const sourcePrograms = {};
  for (const c of cards) {
    sourcePrograms[c.id] = {
      label: c.label,
      bank: c.bank,
      tier: c.tier,
      earnRate: c.earn_rate,
      baseInr: c.base_inr,
    };
  }

  // Build partner lookup
  const partnersById = {};
  for (const p of partners) {
    partnersById[p.id] = p;
  }

  // Build REDEMPTION_OPTIONS — denormalize: one entry per partner, sources = all cards that transfer to it
  const redemptionOptions = partners.map(p => {
    const cardSources = {};
    for (const c of cards) {
      const edge = (c.transfers || []).find(t => t.partner === p.id);
      if (edge) {
        cardSources[c.id] = { ratio: edge.ratio, note: edge.note };
      }
    }

    return {
      category: p.category,
      partner: p.name,
      sources: cardSources,
      sweetSpot: {
        example: p.sweet_spot.example,
        milesNeeded: p.sweet_spot.miles_needed,
        cashValueInr: p.sweet_spot.cash_value_inr,
        cabin: p.sweet_spot.cabin,
        taxesInr: p.sweet_spot.taxes_inr,
      },
      valuation: p.valuation,
      deepLink: p.deep_link || '',
      dynamicPricing: p.dynamic_pricing,
      tags: p.tags || [],
      lastVerified: p.last_verified,
      dataSources: (p.sources || []).map(s => s.name),
    };
  });

  const dataFile = `// Auto-generated by scripts/build-data.js. Do not edit directly.
// Edit YAML files in /data/ and run: npm run build:data

export const SOURCE_PROGRAMS = ${JSON.stringify(sourcePrograms, null, 2)};

export const REDEMPTION_OPTIONS = ${JSON.stringify(redemptionOptions, null, 2)};

export const DATA_SOURCES = ${JSON.stringify(sources, null, 2)};

export const META = {
  cardCount: ${cards.length},
  partnerCount: ${partners.length},
  sourceCount: ${sources.length},
  builtAt: "${new Date().toISOString()}"
};
`;

  fs.writeFileSync(OUTPUT, dataFile);
  console.log(`✓ Wrote ${OUTPUT}`);
}

main();
