// Auto-generated by scripts/build-data.js. Do not edit directly.
// Edit YAML files in /data/ and run: npm run build:data

export const SOURCE_PROGRAMS = {
  "amex_gold": {
    "label": "Amex Gold Charge",
    "bank": "American Express",
    "tier": "Premium",
    "earnRate": "1 MR / ₹40",
    "baseInr": 0.5
  },
  "amex_mrcc": {
    "label": "Amex Membership Rewards (MRCC)",
    "bank": "American Express",
    "tier": "Entry",
    "earnRate": "1 MR / ₹50",
    "baseInr": 0.25
  },
  "amex_platinum_reserve": {
    "label": "Amex Platinum Reserve",
    "bank": "American Express",
    "tier": "Super Premium",
    "earnRate": "1 MR / ₹40",
    "baseInr": 0.5
  },
  "amex_platinum_travel": {
    "label": "Amex Platinum Travel",
    "bank": "American Express",
    "tier": "Premium",
    "earnRate": "1 MR / ₹50 + milestones",
    "baseInr": 0.5
  },
  "amex_platinum": {
    "label": "Amex Platinum Charge",
    "bank": "American Express",
    "tier": "Invitation",
    "earnRate": "1 MR / ₹40",
    "baseInr": 0.5
  },
  "au_zenith_plus": {
    "label": "AU Zenith+",
    "bank": "AU Small Finance",
    "tier": "Super Premium",
    "earnRate": "2 RP / ₹100 + 2X travel",
    "baseInr": 0.4
  },
  "au_zenith": {
    "label": "AU Zenith",
    "bank": "AU Small Finance",
    "tier": "Premium",
    "earnRate": "2 RP / ₹100",
    "baseInr": 0.3
  },
  "axis_atlas": {
    "label": "Axis Atlas",
    "bank": "Axis Bank",
    "tier": "Super Premium",
    "earnRate": "2 EDGE Miles / ₹100",
    "baseInr": 1
  },
  "axis_burgundy": {
    "label": "Axis Burgundy Private",
    "bank": "Axis Bank",
    "tier": "Invitation",
    "earnRate": "10 EDGE / ₹200",
    "baseInr": 0.25
  },
  "axis_horizon": {
    "label": "Axis Horizon",
    "bank": "Axis Bank",
    "tier": "Premium",
    "earnRate": "2 Miles / ₹200 (travel)",
    "baseInr": 1
  },
  "axis_magnus": {
    "label": "Axis Magnus",
    "bank": "Axis Bank",
    "tier": "Premium",
    "earnRate": "12 EDGE / ₹200 (post-2023)",
    "baseInr": 0.2
  },
  "axis_olympus": {
    "label": "Axis Olympus",
    "bank": "Axis Bank",
    "tier": "Invitation",
    "earnRate": "3 Miles / ₹100",
    "baseInr": 1
  },
  "axis_reserve": {
    "label": "Axis Reserve",
    "bank": "Axis Bank",
    "tier": "Super Premium",
    "earnRate": "15 EDGE / ₹200",
    "baseInr": 0.2
  },
  "hdfc_bizblack": {
    "label": "HDFC BizBlack",
    "bank": "HDFC Bank",
    "tier": "Business",
    "earnRate": "5 RP / ₹150",
    "baseInr": 1
  },
  "hdfc_bizpower": {
    "label": "HDFC Biz Power",
    "bank": "HDFC Bank",
    "tier": "Business",
    "earnRate": "5 RP / ₹150 (capped)",
    "baseInr": 0.5
  },
  "hdfc_dcb": {
    "label": "HDFC Diners Club Black",
    "bank": "HDFC Bank",
    "tier": "Super Premium",
    "earnRate": "5 RP / ₹150",
    "baseInr": 1
  },
  "hdfc_infinia": {
    "label": "HDFC Infinia",
    "bank": "HDFC Bank",
    "tier": "Super Premium",
    "earnRate": "5 RP / ₹150",
    "baseInr": 1
  },
  "hdfc_marriott": {
    "label": "HDFC Marriott Bonvoy",
    "bank": "HDFC Bank",
    "tier": "Co-brand",
    "earnRate": "8 Bonvoy / ₹150 (hotel)",
    "baseInr": 0.5
  },
  "hdfc_regalia": {
    "label": "HDFC Regalia Gold",
    "bank": "HDFC Bank",
    "tier": "Premium",
    "earnRate": "4 RP / ₹150",
    "baseInr": 0.5
  },
  "hsbc_live_plus": {
    "label": "HSBC Live+",
    "bank": "HSBC India",
    "tier": "Entry",
    "earnRate": "10% dining / 1.5% other",
    "baseInr": 1
  },
  "hsbc_premier_metal": {
    "label": "HSBC Premier Metal",
    "bank": "HSBC India",
    "tier": "Super Premium",
    "earnRate": "3 RP / ₹100 + Taj benefits",
    "baseInr": 0.5
  },
  "hsbc_premier": {
    "label": "HSBC Premier",
    "bank": "HSBC India",
    "tier": "Premium",
    "earnRate": "3 RP / ₹100",
    "baseInr": 0.25
  },
  "hsbc_travel_one": {
    "label": "HSBC TravelOne",
    "bank": "HSBC India",
    "tier": "Premium",
    "earnRate": "4 points / ₹100 travel",
    "baseInr": 1
  },
  "icici_amazon_pay": {
    "label": "Amazon Pay ICICI",
    "bank": "ICICI Bank",
    "tier": "Entry",
    "earnRate": "5% Amazon Prime / 2% others",
    "baseInr": 1
  },
  "icici_emeralde_std": {
    "label": "ICICI Emeralde",
    "bank": "ICICI Bank",
    "tier": "Super Premium",
    "earnRate": "4 RP / ₹100",
    "baseInr": 0.6
  },
  "icici_emeralde": {
    "label": "ICICI Emeralde Private Metal",
    "bank": "ICICI Bank",
    "tier": "Invitation",
    "earnRate": "6 RP / ₹200",
    "baseInr": 1
  },
  "icici_sapphiro": {
    "label": "ICICI Sapphiro",
    "bank": "ICICI Bank",
    "tier": "Premium",
    "earnRate": "2-6 RP / ₹100",
    "baseInr": 0.25
  },
  "idfc_private": {
    "label": "IDFC First Private",
    "bank": "IDFC FIRST",
    "tier": "Invitation",
    "earnRate": "10X online / 6X offline",
    "baseInr": 0.25
  },
  "idfc_wealth": {
    "label": "IDFC First Wealth",
    "bank": "IDFC FIRST",
    "tier": "Premium",
    "earnRate": "10X online / 6X offline",
    "baseInr": 0.25
  },
  "indusind_avios": {
    "label": "IndusInd Avios Visa Infinite",
    "bank": "IndusInd Bank",
    "tier": "Co-brand",
    "earnRate": "1.5 Avios / ₹100",
    "baseInr": 1
  },
  "indusind_legend": {
    "label": "IndusInd Legend",
    "bank": "IndusInd Bank",
    "tier": "Premium",
    "earnRate": "2 RP / ₹100",
    "baseInr": 0.5
  },
  "indusind_pinnacle": {
    "label": "IndusInd Pinnacle",
    "bank": "IndusInd Bank",
    "tier": "Super Premium",
    "earnRate": "2.5 RP / ₹100",
    "baseInr": 0.5
  },
  "kotak_solitaire": {
    "label": "Kotak Solitaire",
    "bank": "Kotak Mahindra",
    "tier": "Invitation",
    "earnRate": "12 Air Miles / ₹100",
    "baseInr": 1
  },
  "kotak_white_res": {
    "label": "Kotak White Reserve",
    "bank": "Kotak Mahindra",
    "tier": "Premium",
    "earnRate": "8 Air Miles / ₹100",
    "baseInr": 0.75
  },
  "kotak_white": {
    "label": "Kotak White",
    "bank": "Kotak Mahindra",
    "tier": "Premium",
    "earnRate": "4 Reward Miles / ₹150",
    "baseInr": 0.5
  },
  "rbl_icon": {
    "label": "RBL Icon",
    "bank": "RBL Bank",
    "tier": "Premium",
    "earnRate": "2 RP / ₹100",
    "baseInr": 0.25
  },
  "sbi_airindia_sig": {
    "label": "Air India SBI Signature",
    "bank": "SBI Card",
    "tier": "Co-brand",
    "earnRate": "30 Maharaja / ₹100 (AI)",
    "baseInr": 0.5
  },
  "sbi_aurum": {
    "label": "SBI Aurum",
    "bank": "SBI Card",
    "tier": "Invitation",
    "earnRate": "4 RP / ₹100 + 10X online",
    "baseInr": 0.25
  },
  "sbi_cashback": {
    "label": "SBI Cashback",
    "bank": "SBI Card",
    "tier": "Entry",
    "earnRate": "5% online cashback",
    "baseInr": 1
  },
  "sbi_elite": {
    "label": "SBI ELITE",
    "bank": "SBI Card",
    "tier": "Premium",
    "earnRate": "2 RP / ₹100 + 5X dining",
    "baseInr": 0.25
  },
  "sbi_etihad_prem": {
    "label": "Etihad Guest SBI Premier",
    "bank": "SBI Card",
    "tier": "Co-brand",
    "earnRate": "6 Etihad Guest / $1 intl",
    "baseInr": 0.5
  },
  "sbi_prime": {
    "label": "SBI PRIME",
    "bank": "SBI Card",
    "tier": "Premium",
    "earnRate": "2 RP / ₹100 + 10X dining",
    "baseInr": 0.25
  },
  "sc_emirates": {
    "label": "StanC Emirates World",
    "bank": "Standard Chartered",
    "tier": "Co-brand",
    "earnRate": "10 Skywards / ₹150 (Emirates)",
    "baseInr": 0.5
  },
  "sc_ultimate": {
    "label": "StanC Ultimate",
    "bank": "Standard Chartered",
    "tier": "Super Premium",
    "earnRate": "5 RP / ₹150",
    "baseInr": 0.33
  },
  "tata_neu_inf": {
    "label": "Tata Neu Infinity HDFC",
    "bank": "HDFC / Tata",
    "tier": "Co-brand",
    "earnRate": "5% Tata / 1.5% else",
    "baseInr": 1
  },
  "tata_neu_plus": {
    "label": "Tata Neu Plus HDFC",
    "bank": "HDFC / Tata",
    "tier": "Co-brand",
    "earnRate": "2% Tata / 1% else",
    "baseInr": 1
  },
  "yes_marquee": {
    "label": "YES Marquee",
    "bank": "Yes Bank",
    "tier": "Invitation",
    "earnRate": "12 RP / ₹200",
    "baseInr": 0.25
  },
  "yes_private": {
    "label": "YES Private",
    "bank": "Yes Bank",
    "tier": "Invitation",
    "earnRate": "24 RP / ₹200",
    "baseInr": 0.25
  },
  "yes_reserv": {
    "label": "YES Reserv",
    "bank": "Yes Bank",
    "tier": "Premium",
    "earnRate": "8 RP / ₹200",
    "baseInr": 0.25
  }
};

export const REDEMPTION_OPTIONS = [
  {
    "category": "luxury_hotel",
    "partner": "Accor ALL (Sofitel / Raffles)",
    "sources": {
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1 devalued 2024"
      },
      "hsbc_premier_metal": {
        "ratio": 1,
        "note": "1:1 (HSBC special)"
      },
      "sbi_aurum": {
        "ratio": 1,
        "note": "1:1 direct"
      }
    },
    "sweetSpot": {
      "example": "Sofitel BKC / Raffles Udaipur",
      "milesNeeded": 20000,
      "cashValueInr": 36000,
      "cabin": "Any room",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1.8,
      "realistic": 1.8,
      "ceiling": 1.8
    },
    "deepLink": "https://all.accor.com/usa/index.en.shtml",
    "dynamicPricing": false,
    "tags": [
      "Fixed 2000=€40",
      "Raffles/Fairmont"
    ],
    "lastVerified": "2026-04-11",
    "dataSources": [
      "AwardWallet",
      "Accor Direct"
    ]
  },
  {
    "category": "mid_hotel",
    "partner": "Accor ALL (Novotel / ibis)",
    "sources": {
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hsbc_premier_metal": {
        "ratio": 1,
        "note": "1:1"
      },
      "sbi_aurum": {
        "ratio": 1,
        "note": "1:1"
      }
    },
    "sweetSpot": {
      "example": "Novotel Mumbai/Goa — 1 night",
      "milesNeeded": 8000,
      "cashValueInr": 14400,
      "cabin": "Standard",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1.8,
      "realistic": 1.8,
      "ceiling": 1.8
    },
    "deepLink": "https://all.accor.com/usa/index.en.shtml",
    "dynamicPricing": false,
    "tags": [
      "Fixed rate",
      "Wide India network"
    ],
    "lastVerified": "2026-04-11",
    "dataSources": [
      "Accor Direct",
      "PointsMath"
    ]
  },
  {
    "category": "domestic_flight",
    "partner": "Air India Maharaja Club",
    "sources": {
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "au_zenith_plus": {
        "ratio": 0.67,
        "note": "3:2 Maharaja"
      },
      "axis_atlas": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "axis_magnus": {
        "ratio": 0.4,
        "note": "5:2"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "icici_emeralde_std": {
        "ratio": 0.67,
        "note": "3:2"
      },
      "icici_emeralde": {
        "ratio": 1,
        "note": "1:1 direct"
      },
      "kotak_solitaire": {
        "ratio": 1,
        "note": "1:1 Air Miles"
      },
      "sbi_airindia_sig": {
        "ratio": 1,
        "note": "Direct earn"
      },
      "sbi_aurum": {
        "ratio": 0.2,
        "note": "5:1"
      }
    },
    "sweetSpot": {
      "example": "DEL → BOM Economy (new chart)",
      "milesNeeded": 7500,
      "cashValueInr": 8500,
      "cabin": "Economy",
      "taxesInr": 1500
    },
    "valuation": {
      "floor": 0.8,
      "realistic": 1.2,
      "ceiling": 2
    },
    "deepLink": "https://www.airindia.com/in/en/maharaja-club.html",
    "dynamicPricing": false,
    "tags": [
      "No fuel surcharge",
      "Post-Apr 2026 cheaper"
    ],
    "lastVerified": "2026-04-21",
    "dataSources": [
      "Magnify.club",
      "Aviation A2Z"
    ]
  },
  {
    "category": "experiences",
    "partner": "Amex Taj 24K Gold Collection",
    "sources": {
      "amex_gold": {
        "ratio": 0.58,
        "note": "24K MR = ₹14K voucher"
      },
      "amex_mrcc": {
        "ratio": 0.58,
        "note": "24K MR = ₹14K voucher"
      },
      "amex_platinum_travel": {
        "ratio": 0.58,
        "note": "24K MR = ₹14K"
      },
      "amex_platinum": {
        "ratio": 0.58,
        "note": "24K MR = ₹14K"
      }
    },
    "sweetSpot": {
      "example": "Taj ₹14,000 stay voucher",
      "milesNeeded": 24000,
      "cashValueInr": 14000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.58,
      "realistic": 0.58,
      "ceiling": 0.58
    },
    "deepLink": "https://www.americanexpress.com/in/benefits/taj-experiences/",
    "dynamicPricing": false,
    "tags": [
      "Best Amex India value",
      "Fixed"
    ],
    "lastVerified": "2026-04-19",
    "dataSources": [
      "LiveFromALounge",
      "Amex India"
    ]
  },
  {
    "category": "shopping",
    "partner": "Apple Products (HDFC)",
    "sources": {
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1 product/qtr cap"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1 product/qtr cap"
      }
    },
    "sweetSpot": {
      "example": "iPhone/MacBook partial",
      "milesNeeded": 50000,
      "cashValueInr": 50000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/apple-products",
    "dynamicPricing": false,
    "tags": [
      "Quarterly cap",
      "Liquidation"
    ],
    "lastVerified": "2026-04-18",
    "dataSources": [
      "Business Standard",
      "HDFC Direct"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Avianca LifeMiles",
    "sources": {
      "hdfc_bizblack": {
        "ratio": 0.5,
        "note": "2:1 HDFC-exclusive"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1 HDFC-exclusive"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1 HDFC-exclusive"
      }
    },
    "sweetSpot": {
      "example": "DEL → Europe Economy (Star)",
      "milesNeeded": 30000,
      "cashValueInr": 55000,
      "cabin": "Economy",
      "taxesInr": 3500
    },
    "valuation": {
      "floor": 0.8,
      "realistic": 1.5,
      "ceiling": 2.5
    },
    "deepLink": "https://www.lifemiles.com/",
    "dynamicPricing": false,
    "tags": [
      "No fuel surcharge",
      "HDFC-only",
      "Regular sales"
    ],
    "lastVerified": "2026-04-12",
    "dataSources": [
      "LoyaltyLobby",
      "PointsMath"
    ]
  },
  {
    "category": "package",
    "partner": "Axis Travel EDGE",
    "sources": {
      "axis_atlas": {
        "ratio": 1,
        "note": "1 Mile = ₹1"
      },
      "axis_horizon": {
        "ratio": 1,
        "note": "1 Mile = ₹1"
      },
      "axis_olympus": {
        "ratio": 1,
        "note": "1 Mile = ₹1"
      }
    },
    "sweetSpot": {
      "example": "Flight + hotel bundle",
      "milesNeeded": 10000,
      "cashValueInr": 10000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.axisbank.com/retail/cards/credit-card/travel-edge",
    "dynamicPricing": false,
    "tags": [
      "Cash-equivalent",
      "20X Travel EDGE"
    ],
    "lastVerified": "2026-04-17",
    "dataSources": [
      "Axis Direct"
    ]
  },
  {
    "category": "experiences",
    "partner": "BookMyShow / Concerts",
    "sources": {
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 ticket credit"
      },
      "sbi_aurum": {
        "ratio": 0.25,
        "note": "Floor rate"
      },
      "yes_marquee": {
        "ratio": 0.3,
        "note": "Partial"
      },
      "yes_private": {
        "ratio": 0.3,
        "note": "Partial"
      }
    },
    "sweetSpot": {
      "example": "Concert/movie tickets",
      "milesNeeded": 1000,
      "cashValueInr": 800,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.25,
      "realistic": 0.8,
      "ceiling": 1
    },
    "deepLink": "https://in.bookmyshow.com/",
    "dynamicPricing": false,
    "tags": [
      "Easy redemption",
      "Small denominations"
    ],
    "lastVerified": "2026-04-12",
    "dataSources": [
      "Bank portals"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "British Airways Executive Club / Avios",
    "sources": {
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "axis_magnus": {
        "ratio": 0.2,
        "note": "5:1 (post-Apr 2026)"
      },
      "axis_reserve": {
        "ratio": 0.2,
        "note": "5:1"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "indusind_avios": {
        "ratio": 1.5,
        "note": "1.5 Avios/₹100 direct"
      }
    },
    "sweetSpot": {
      "example": "BOM → DXB Y on Qatar partner",
      "milesNeeded": 9000,
      "cashValueInr": 32000,
      "cabin": "Economy",
      "taxesInr": 4500
    },
    "valuation": {
      "floor": 0.8,
      "realistic": 1.5,
      "ceiling": 3.5
    },
    "deepLink": "https://www.britishairways.com/travel/loyalty-executive-club/public/en_gb",
    "dynamicPricing": false,
    "tags": [
      "Distance-based",
      "High YQ on BA metal",
      "Qatar access"
    ],
    "lastVerified": "2026-04-18",
    "dataSources": [
      "AwardFares",
      "PointsMath"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Cathay Asia Miles",
    "sources": {
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      }
    },
    "sweetSpot": {
      "example": "BOM → HKG Business",
      "milesNeeded": 45000,
      "cashValueInr": 110000,
      "cabin": "Business",
      "taxesInr": 8500
    },
    "valuation": {
      "floor": 1,
      "realistic": 1.8,
      "ceiling": 2.8
    },
    "deepLink": "https://www.cathaypacific.com/cx/en_IN/asia-miles.html",
    "dynamicPricing": false,
    "tags": [
      "oneworld",
      "Good J availability"
    ],
    "lastVerified": "2026-04-16",
    "dataSources": [
      "PointsMath",
      "AwardFares"
    ]
  },
  {
    "category": "mid_hotel",
    "partner": "Club ITC Green Points",
    "sources": {
      "hdfc_dcb": {
        "ratio": 0.67,
        "note": "3:2"
      },
      "hdfc_infinia": {
        "ratio": 0.67,
        "note": "3:2 via SmartBuy"
      },
      "tata_neu_inf": {
        "ratio": 1,
        "note": "1:1 via Tata ecosystem"
      }
    },
    "sweetSpot": {
      "example": "Welcomhotel / Fortune — 1 night",
      "milesNeeded": 8000,
      "cashValueInr": 7500,
      "cabin": "Standard",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.8,
      "realistic": 1,
      "ceiling": 1.2
    },
    "deepLink": "https://www.itchotels.com/in/en/club-itc",
    "dynamicPricing": false,
    "tags": [
      "Post-demerger program",
      "Welcomhotel/Fortune"
    ],
    "lastVerified": "2026-04-13",
    "dataSources": [
      "Hotelier India",
      "ITC Direct"
    ]
  },
  {
    "category": "shopping",
    "partner": "Croma / Reliance Digital (Tata)",
    "sources": {
      "tata_neu_inf": {
        "ratio": 1,
        "note": "5% base + offers"
      },
      "tata_neu_plus": {
        "ratio": 1,
        "note": "2% base"
      }
    },
    "sweetSpot": {
      "example": "Electronics / appliances",
      "milesNeeded": 10000,
      "cashValueInr": 10000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.croma.com/",
    "dynamicPricing": false,
    "tags": [
      "NeuCoins direct",
      "Tata ecosystem"
    ],
    "lastVerified": "2026-04-15",
    "dataSources": [
      "Tata Neu"
    ]
  },
  {
    "category": "cashback",
    "partner": "Direct Cashback (SBI/IDFC/Amazon Pay)",
    "sources": {
      "icici_amazon_pay": {
        "ratio": 1,
        "note": "5% Amazon Prime"
      },
      "idfc_wealth": {
        "ratio": 1,
        "note": "Embedded cashback"
      },
      "sbi_cashback": {
        "ratio": 1,
        "note": "5% on online spend"
      }
    },
    "sweetSpot": {
      "example": "Automatic cash credit",
      "milesNeeded": 10000,
      "cashValueInr": 10000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "",
    "dynamicPricing": false,
    "tags": [
      "No effort",
      "Best floor rate"
    ],
    "lastVerified": "2026-04-19",
    "dataSources": [
      "Bank direct"
    ]
  },
  {
    "category": "domestic_flight",
    "partner": "Vistara/Akasa Portal Bookings",
    "sources": {
      "axis_atlas": {
        "ratio": 1,
        "note": "Travel EDGE"
      },
      "axis_horizon": {
        "ratio": 1,
        "note": "Travel EDGE"
      },
      "icici_emeralde": {
        "ratio": 1,
        "note": "iShop 6X"
      }
    },
    "sweetSpot": {
      "example": "Any domestic booking",
      "milesNeeded": 5000,
      "cashValueInr": 5000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "",
    "dynamicPricing": false,
    "tags": [
      "Flexible dates"
    ],
    "lastVerified": "2026-04-15",
    "dataSources": [
      "Bank portals"
    ]
  },
  {
    "category": "experiences",
    "partner": "EazyDiner Fine Dining",
    "sources": {
      "axis_magnus": {
        "ratio": 0.3,
        "note": "Voucher rate"
      },
      "hdfc_dcb": {
        "ratio": 0.8,
        "note": "Partial"
      },
      "hdfc_infinia": {
        "ratio": 0.8,
        "note": "Partial redemption"
      },
      "hsbc_live_plus": {
        "ratio": 1,
        "note": "10% dining base"
      },
      "indusind_pinnacle": {
        "ratio": 0.5,
        "note": "Via portal"
      }
    },
    "sweetSpot": {
      "example": "Fine-dining ₹5000 voucher",
      "milesNeeded": 5000,
      "cashValueInr": 5000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.3,
      "realistic": 0.8,
      "ceiling": 1
    },
    "deepLink": "https://www.eazydiner.com/",
    "dynamicPricing": false,
    "tags": [
      "5-star dining",
      "Variable"
    ],
    "lastVerified": "2026-04-13",
    "dataSources": [
      "CardInsider"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Emirates Skywards",
    "sources": {
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "sc_emirates": {
        "ratio": 1,
        "note": "1:1 direct earn"
      }
    },
    "sweetSpot": {
      "example": "BOM → DXB Economy Saver",
      "milesNeeded": 22500,
      "cashValueInr": 24000,
      "cabin": "Economy",
      "taxesInr": 21000
    },
    "valuation": {
      "floor": 0.4,
      "realistic": 0.8,
      "ceiling": 1.5
    },
    "deepLink": "https://www.emirates.com/english/skywards/",
    "dynamicPricing": false,
    "tags": [
      "High YQ",
      "Often cheaper to buy cash",
      "Co-brand earn"
    ],
    "lastVerified": "2026-04-14",
    "dataSources": [
      "AwardWallet",
      "LiveFromALounge"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Etihad Guest",
    "sources": {
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1 (ending Jun 2026)"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 (via SmartBuy)"
      },
      "sbi_etihad_prem": {
        "ratio": 1,
        "note": "1:1 direct earn"
      }
    },
    "sweetSpot": {
      "example": "BOM → AUH Business Saver",
      "milesNeeded": 44000,
      "cashValueInr": 95000,
      "cabin": "Business",
      "taxesInr": 12000
    },
    "valuation": {
      "floor": 0.6,
      "realistic": 1.4,
      "ceiling": 2.2
    },
    "deepLink": "https://www.etihad.com/en-in/etihad-guest",
    "dynamicPricing": false,
    "tags": [
      "AA partner access",
      "Ending at Amex Jun 2026"
    ],
    "lastVerified": "2026-04-17",
    "dataSources": [
      "One Mile at a Time",
      "LiveFromALounge"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Air France–KLM Flying Blue",
    "sources": {
      "amex_gold": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum_travel": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "axis_atlas": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "axis_burgundy": {
        "ratio": 0.8,
        "note": "5:4"
      },
      "axis_reserve": {
        "ratio": 0.4,
        "note": "5:2"
      },
      "hdfc_bizblack": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_regalia": {
        "ratio": 0.33,
        "note": "3:1"
      },
      "hsbc_premier_metal": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "kotak_solitaire": {
        "ratio": 0.5,
        "note": "2:1"
      }
    },
    "sweetSpot": {
      "example": "DEL → CDG/AMS Economy (Promo)",
      "milesNeeded": 22500,
      "cashValueInr": 55000,
      "cabin": "Economy",
      "taxesInr": 7500
    },
    "valuation": {
      "floor": 1,
      "realistic": 1.8,
      "ceiling": 2.5
    },
    "deepLink": "https://www.airfrance.co.in/reward-flights",
    "dynamicPricing": true,
    "tags": [
      "Monthly Promo Rewards",
      "25% off saver",
      "SkyTeam"
    ],
    "lastVerified": "2026-04-20",
    "dataSources": [
      "Magnify.club",
      "AwardWallet"
    ]
  },
  {
    "category": "domestic_flight",
    "partner": "HDFC SmartBuy Flights",
    "sources": {
      "hdfc_bizblack": {
        "ratio": 1,
        "note": "10X multiplier"
      },
      "hdfc_bizpower": {
        "ratio": 0.5,
        "note": "Capped"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "10X multiplier"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "10X multiplier"
      },
      "hdfc_regalia": {
        "ratio": 0.5,
        "note": "Halved multiplier"
      }
    },
    "sweetSpot": {
      "example": "Metro-metro domestic route",
      "milesNeeded": 5000,
      "cashValueInr": 5000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://offers.smartbuy.hdfcbank.com/flights",
    "dynamicPricing": false,
    "tags": [
      "Any airline",
      "Cleartrip backend",
      "Cash-equivalent"
    ],
    "lastVerified": "2026-04-20",
    "dataSources": [
      "CardMaven",
      "HDFC Direct"
    ]
  },
  {
    "category": "package",
    "partner": "HDFC SmartBuy (Flight+Hotel)",
    "sources": {
      "hdfc_bizblack": {
        "ratio": 1,
        "note": "10X"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "10X"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "10X on flights & hotels"
      },
      "hdfc_regalia": {
        "ratio": 0.5,
        "note": "Halved"
      }
    },
    "sweetSpot": {
      "example": "Any domestic/intl flight+hotel",
      "milesNeeded": 10000,
      "cashValueInr": 10000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://offers.smartbuy.hdfcbank.com/",
    "dynamicPricing": false,
    "tags": [
      "Flexible dates",
      "Any provider",
      "Guaranteed"
    ],
    "lastVerified": "2026-04-20",
    "dataSources": [
      "HDFC Direct"
    ]
  },
  {
    "category": "mid_hotel",
    "partner": "Hilton Honors",
    "sources": {
      "amex_mrcc": {
        "ratio": 1,
        "note": "1:1 verify in-app"
      },
      "amex_platinum": {
        "ratio": 1,
        "note": "1:1"
      }
    },
    "sweetSpot": {
      "example": "Hilton Goa Resort — 1 night",
      "milesNeeded": 60000,
      "cashValueInr": 16000,
      "cabin": "Standard",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.2,
      "realistic": 0.3,
      "ceiling": 0.45
    },
    "deepLink": "https://www.hilton.com/",
    "dynamicPricing": true,
    "tags": [
      "5th night free",
      "Dynamic"
    ],
    "lastVerified": "2026-04-09",
    "dataSources": [
      "WalletHub",
      "Amex India"
    ]
  },
  {
    "category": "package",
    "partner": "ICICI iShop",
    "sources": {
      "icici_emeralde_std": {
        "ratio": 0.67,
        "note": "3:2"
      },
      "icici_emeralde": {
        "ratio": 1,
        "note": "6X flights / 12X hotels"
      }
    },
    "sweetSpot": {
      "example": "Flight + hotel vouchers",
      "milesNeeded": 10000,
      "cashValueInr": 10000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://ishop.icicibank.com/",
    "dynamicPricing": false,
    "tags": [
      "Accelerator portal",
      "MakeMyTrip backend"
    ],
    "lastVerified": "2026-04-15",
    "dataSources": [
      "LiveFromALounge",
      "ICICI Direct"
    ]
  },
  {
    "category": "luxury_hotel",
    "partner": "IHG (Six Senses / InterCon)",
    "sources": {
      "axis_atlas": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      }
    },
    "sweetSpot": {
      "example": "Six Senses Fort Barwara — 1 night",
      "milesNeeded": 80000,
      "cashValueInr": 65000,
      "cabin": "Standard",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.35,
      "realistic": 0.6,
      "ceiling": 1
    },
    "deepLink": "https://www.ihg.com/onerewards/content/in/en/redeem-points",
    "dynamicPricing": true,
    "tags": [
      "4th night free",
      "Six Senses"
    ],
    "lastVerified": "2026-04-14",
    "dataSources": [
      "PointsMath",
      "CardExpert"
    ]
  },
  {
    "category": "domestic_flight",
    "partner": "IndiGo BluChip",
    "sources": {
      "axis_atlas": {
        "ratio": 1,
        "note": "via Travel EDGE"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "via SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "via SmartBuy"
      }
    },
    "sweetSpot": {
      "example": "Metro-metro economy Saver",
      "milesNeeded": 4000,
      "cashValueInr": 4500,
      "cabin": "Economy",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.9,
      "realistic": 1,
      "ceiling": 1.2
    },
    "deepLink": "https://www.goindigo.in/bluchip.html",
    "dynamicPricing": true,
    "tags": [
      "Largest domestic network",
      "Dynamic"
    ],
    "lastVerified": "2026-04-16",
    "dataSources": [
      "CardInsider"
    ]
  },
  {
    "category": "luxury_hotel",
    "partner": "Marriott Bonvoy (Luxury Collection)",
    "sources": {
      "amex_gold": {
        "ratio": 1,
        "note": "1:1"
      },
      "amex_mrcc": {
        "ratio": 1,
        "note": "1:1 best Indian path"
      },
      "amex_platinum_travel": {
        "ratio": 1,
        "note": "1:1"
      },
      "amex_platinum": {
        "ratio": 1,
        "note": "1:1"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_marriott": {
        "ratio": 1,
        "note": "Direct co-brand earn"
      },
      "hdfc_regalia": {
        "ratio": 0.33,
        "note": "3:1"
      },
      "hsbc_premier_metal": {
        "ratio": 1,
        "note": "1:1"
      },
      "kotak_solitaire": {
        "ratio": 0.33,
        "note": "3:1"
      }
    },
    "sweetSpot": {
      "example": "ITC Grand Chola / Maurya — 1 night",
      "milesNeeded": 50000,
      "cashValueInr": 28000,
      "cabin": "Standard room",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.35,
      "realistic": 0.55,
      "ceiling": 1
    },
    "deepLink": "https://www.marriott.com/loyalty/redeem/travel.mi",
    "dynamicPricing": true,
    "tags": [
      "5th night free",
      "ITC access",
      "Airline hub"
    ],
    "lastVerified": "2026-04-20",
    "dataSources": [
      "LiveFromALounge",
      "MilesCop"
    ]
  },
  {
    "category": "mid_hotel",
    "partner": "Marriott Bonvoy (Courtyard/Fairfield)",
    "sources": {
      "amex_gold": {
        "ratio": 1,
        "note": "1:1"
      },
      "amex_mrcc": {
        "ratio": 1,
        "note": "1:1"
      },
      "amex_platinum": {
        "ratio": 1,
        "note": "1:1"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_marriott": {
        "ratio": 1,
        "note": "Direct earn"
      }
    },
    "sweetSpot": {
      "example": "Le Méridien Kochi / Courtyard",
      "milesNeeded": 17500,
      "cashValueInr": 8500,
      "cabin": "Standard",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.3,
      "realistic": 0.5,
      "ceiling": 0.8
    },
    "deepLink": "https://www.marriott.com/loyalty/redeem/travel.mi",
    "dynamicPricing": true,
    "tags": [
      "5th night free",
      "Cat 1-3"
    ],
    "lastVerified": "2026-04-18",
    "dataSources": [
      "CardInsider"
    ]
  },
  {
    "category": "package",
    "partner": "MakeMyTrip / Yatra (via IDFC/AU)",
    "sources": {
      "au_zenith_plus": {
        "ratio": 0.4,
        "note": "Voucher rate"
      },
      "idfc_private": {
        "ratio": 0.5,
        "note": "10X online"
      },
      "idfc_wealth": {
        "ratio": 0.5,
        "note": "10X online rewards"
      }
    },
    "sweetSpot": {
      "example": "Flight + hotel package bookings",
      "milesNeeded": 10000,
      "cashValueInr": 5000,
      "cabin": "Any",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.4,
      "realistic": 0.5,
      "ceiling": 0.6
    },
    "deepLink": "https://www.makemytrip.com/",
    "dynamicPricing": false,
    "tags": [
      "IDFC/AU vouchers",
      "OTA redemption"
    ],
    "lastVerified": "2026-04-14",
    "dataSources": [
      "CardInsider"
    ]
  },
  {
    "category": "luxury_hotel",
    "partner": "Oberoi One",
    "sources": {
      "amex_platinum": {
        "ratio": 1,
        "note": "via The Hotel Collection"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "via SmartBuy voucher"
      }
    },
    "sweetSpot": {
      "example": "The Oberoi Udaivilas — 1 night",
      "milesNeeded": 85000,
      "cashValueInr": 85000,
      "cabin": "Luxury",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.oberoihotels.com/oberoi-one/",
    "dynamicPricing": false,
    "tags": [
      "Voucher-based",
      "Recognition program"
    ],
    "lastVerified": "2026-04-10",
    "dataSources": [
      "MilesCop"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Qatar Privilege Club / Avios",
    "sources": {
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1 BA Avios"
      },
      "amex_platinum_travel": {
        "ratio": 0.5,
        "note": "2:1 BA Avios"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1 BA Avios"
      },
      "axis_burgundy": {
        "ratio": 0.4,
        "note": "5:2 BA Avios"
      },
      "axis_magnus": {
        "ratio": 0.2,
        "note": "5:1 BA Avios"
      },
      "axis_reserve": {
        "ratio": 0.2,
        "note": "5:1 BA Avios"
      },
      "hdfc_bizblack": {
        "ratio": 1,
        "note": "via Finnair Plus 1:1"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "via Finnair Plus 1:1"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "via Finnair Plus 1:1"
      },
      "hsbc_premier_metal": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "kotak_solitaire": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "sbi_aurum": {
        "ratio": 0.2,
        "note": "5:1 direct Qatar"
      }
    },
    "sweetSpot": {
      "example": "DEL/BOM → DOH Qsuite (Off-peak)",
      "milesNeeded": 30000,
      "cashValueInr": 185000,
      "cabin": "Business (Qsuite)",
      "taxesInr": 5500
    },
    "valuation": {
      "floor": 1.5,
      "realistic": 2.8,
      "ceiling": 4.5
    },
    "deepLink": "https://www.qatarairways.com/en-in/privilege-club.html",
    "dynamicPricing": true,
    "tags": [
      "No fuel surcharge",
      "Qsuite",
      "Peak pricing"
    ],
    "lastVerified": "2026-04-15",
    "dataSources": [
      "PointsMath",
      "LiveFromALounge",
      "r/CreditCardsIndia"
    ]
  },
  {
    "category": "shopping",
    "partner": "Amazon / Flipkart Vouchers",
    "sources": {
      "amex_mrcc": {
        "ratio": 1,
        "note": "₹0.50/pt"
      },
      "au_zenith_plus": {
        "ratio": 1,
        "note": "₹0.40/pt"
      },
      "axis_magnus": {
        "ratio": 1,
        "note": "₹0.20/pt"
      },
      "axis_reserve": {
        "ratio": 1,
        "note": "₹0.20/pt"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "₹0.50-0.80/pt"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "₹0.50-0.80/pt"
      },
      "hsbc_premier": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "idfc_wealth": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "kotak_white": {
        "ratio": 1,
        "note": "₹0.50/pt"
      },
      "rbl_icon": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "sbi_aurum": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "sbi_elite": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "sbi_prime": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "yes_marquee": {
        "ratio": 1,
        "note": "₹0.25/pt"
      }
    },
    "sweetSpot": {
      "example": "Amazon/Flipkart/Myntra gift card",
      "milesNeeded": 10000,
      "cashValueInr": 5000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.2,
      "realistic": 0.5,
      "ceiling": 0.8
    },
    "deepLink": "",
    "dynamicPricing": false,
    "tags": [
      "Easy liquidation",
      "Below ceiling"
    ],
    "lastVerified": "2026-04-21",
    "dataSources": [
      "Bank portals"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Singapore KrisFlyer",
    "sources": {
      "amex_gold": {
        "ratio": 0.5,
        "note": "2:1 + 18% GST"
      },
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1 + 18% GST"
      },
      "amex_platinum_reserve": {
        "ratio": 0.5,
        "note": "2:1 + 18% GST"
      },
      "amex_platinum_travel": {
        "ratio": 0.5,
        "note": "2:1 + 18% GST"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1 + 18% GST"
      },
      "axis_atlas": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "axis_burgundy": {
        "ratio": 0.8,
        "note": "5:4 — best Axis ratio"
      },
      "axis_horizon": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "axis_magnus": {
        "ratio": 0.4,
        "note": "5:2 Group A"
      },
      "axis_olympus": {
        "ratio": 2,
        "note": "1:2 Group B"
      },
      "axis_reserve": {
        "ratio": 0.4,
        "note": "5:2 Group A"
      },
      "hdfc_bizblack": {
        "ratio": 1,
        "note": "1:1 via myREWARDS"
      },
      "hdfc_bizpower": {
        "ratio": 0.5,
        "note": "2:1 (capped)"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 via myREWARDS"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 via myREWARDS"
      },
      "hdfc_regalia": {
        "ratio": 0.33,
        "note": "3:1"
      },
      "hsbc_premier_metal": {
        "ratio": 0.5,
        "note": "2:1 India MR"
      },
      "kotak_solitaire": {
        "ratio": 0.5,
        "note": "2:1 Air Miles"
      },
      "kotak_white_res": {
        "ratio": 0.5,
        "note": "2:1 Air Miles"
      },
      "sbi_aurum": {
        "ratio": 0.2,
        "note": "5:1 (Qatar pool)"
      }
    },
    "sweetSpot": {
      "example": "DEL/BOM → SIN Business Saver",
      "milesNeeded": 36500,
      "cashValueInr": 120000,
      "cabin": "Business",
      "taxesInr": 8500
    },
    "valuation": {
      "floor": 1.2,
      "realistic": 2,
      "ceiling": 3.3
    },
    "deepLink": "https://www.singaporeair.com/en_UK/in/ppsclub-krisflyer/use-miles/flight-redemption/",
    "dynamicPricing": false,
    "tags": [
      "Star Alliance",
      "Best availability",
      "Stopover allowed"
    ],
    "lastVerified": "2026-04-18",
    "dataSources": [
      "PointsMath",
      "LiveFromALounge"
    ]
  },
  {
    "category": "cashback",
    "partner": "Statement Credit",
    "sources": {
      "amex_gold": {
        "ratio": 1,
        "note": "₹0.50/pt"
      },
      "amex_mrcc": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "amex_platinum": {
        "ratio": 1,
        "note": "₹0.50/pt"
      },
      "axis_burgundy": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "axis_magnus": {
        "ratio": 1,
        "note": "₹0.20/pt"
      },
      "axis_reserve": {
        "ratio": 1,
        "note": "₹0.20/pt"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "₹0.30/pt"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "₹0.30/pt — avoid"
      },
      "hsbc_premier": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "icici_emeralde": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "idfc_wealth": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "rbl_icon": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "sbi_aurum": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "sbi_elite": {
        "ratio": 1,
        "note": "₹0.25/pt"
      },
      "yes_marquee": {
        "ratio": 1,
        "note": "₹0.25/pt"
      }
    },
    "sweetSpot": {
      "example": "Pure cashback (last resort)",
      "milesNeeded": 10000,
      "cashValueInr": 2500,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 0.2,
      "realistic": 0.3,
      "ceiling": 0.5
    },
    "deepLink": "",
    "dynamicPricing": false,
    "tags": [
      "Last resort",
      "Floor value"
    ],
    "lastVerified": "2026-04-20",
    "dataSources": [
      "Bank direct"
    ]
  },
  {
    "category": "experiences",
    "partner": "Taj Epicure / Club Marriott",
    "sources": {
      "amex_platinum": {
        "ratio": 1,
        "note": "Complimentary"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "Complimentary (Infinia)"
      },
      "hsbc_premier_metal": {
        "ratio": 1,
        "note": "Complimentary Taj Epicure"
      }
    },
    "sweetSpot": {
      "example": "Dining membership 25% off",
      "milesNeeded": 0,
      "cashValueInr": 25000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.tajhotels.com/en-in/taj/epicure-programme/",
    "dynamicPricing": false,
    "tags": [
      "Card benefit",
      "Dining discounts",
      "Free with card"
    ],
    "lastVerified": "2026-04-10",
    "dataSources": [
      "CardInsider",
      "LiveFromALounge"
    ]
  },
  {
    "category": "luxury_hotel",
    "partner": "Taj InnerCircle / NeuPass",
    "sources": {
      "amex_platinum_travel": {
        "ratio": 0.58,
        "note": "24K MR = ₹14K voucher"
      },
      "hsbc_premier_metal": {
        "ratio": 1,
        "note": "Direct Taj benefits"
      },
      "tata_neu_inf": {
        "ratio": 1,
        "note": "1 NeuCoin = ₹1"
      },
      "tata_neu_plus": {
        "ratio": 1,
        "note": "1 NeuCoin = ₹1"
      }
    },
    "sweetSpot": {
      "example": "Rambagh Palace / Taj Lake Palace",
      "milesNeeded": 60000,
      "cashValueInr": 60000,
      "cabin": "Heritage room",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.tajhotels.com/en-in/neupass",
    "dynamicPricing": false,
    "tags": [
      "Fixed ₹1/coin",
      "Taj/Vivanta/Ginger"
    ],
    "lastVerified": "2026-04-19",
    "dataSources": [
      "Taj Direct",
      "CardInsider"
    ]
  },
  {
    "category": "shopping",
    "partner": "Tanishq Jewellery (HDFC)",
    "sources": {
      "hdfc_dcb": {
        "ratio": 1,
        "note": "50K RP/qtr cap"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "50K RP/qtr cap"
      },
      "tata_neu_inf": {
        "ratio": 1,
        "note": "Direct ₹1 rate"
      }
    },
    "sweetSpot": {
      "example": "Tanishq jewellery voucher",
      "milesNeeded": 50000,
      "cashValueInr": 50000,
      "cabin": "-",
      "taxesInr": 0
    },
    "valuation": {
      "floor": 1,
      "realistic": 1,
      "ceiling": 1
    },
    "deepLink": "https://www.tanishq.co.in/",
    "dynamicPricing": false,
    "tags": [
      "Quarterly cap",
      "Indian jewellery"
    ],
    "lastVerified": "2026-04-16",
    "dataSources": [
      "HDFC Direct",
      "TechnoFino"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Turkish Miles&Smiles",
    "sources": {
      "axis_magnus": {
        "ratio": 0.4,
        "note": "5:2 Group B"
      },
      "axis_reserve": {
        "ratio": 0.4,
        "note": "5:2 Group B"
      },
      "hdfc_dcb": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      },
      "hdfc_infinia": {
        "ratio": 1,
        "note": "1:1 SmartBuy"
      }
    },
    "sweetSpot": {
      "example": "India → USA Business (partner)",
      "milesNeeded": 52500,
      "cashValueInr": 245000,
      "cabin": "Business",
      "taxesInr": 12000
    },
    "valuation": {
      "floor": 1.5,
      "realistic": 3.5,
      "ceiling": 5
    },
    "deepLink": "https://www.turkishairlines.com/en-in/miles-and-smiles/",
    "dynamicPricing": false,
    "tags": [
      "Fixed chart",
      "Best J to USA",
      "Star Alliance"
    ],
    "lastVerified": "2026-04-10",
    "dataSources": [
      "CardExpert",
      "PointsMath"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "United MileagePlus",
    "sources": {
      "axis_magnus": {
        "ratio": 0.4,
        "note": "5:2"
      },
      "axis_reserve": {
        "ratio": 0.4,
        "note": "5:2"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      }
    },
    "sweetSpot": {
      "example": "DEL → USA Business (Star partner)",
      "milesNeeded": 130000,
      "cashValueInr": 310000,
      "cabin": "Business",
      "taxesInr": 4500
    },
    "valuation": {
      "floor": 0.8,
      "realistic": 1.5,
      "ceiling": 2.3
    },
    "deepLink": "https://www.united.com/en/in/book-flight/award-travel",
    "dynamicPricing": true,
    "tags": [
      "No fuel surcharge",
      "Good search",
      "AI-blocking"
    ],
    "lastVerified": "2026-04-19",
    "dataSources": [
      "NerdWallet",
      "TPG"
    ]
  },
  {
    "category": "intl_flight",
    "partner": "Virgin Atlantic Flying Club",
    "sources": {
      "amex_gold": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_mrcc": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum_travel": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "amex_platinum": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_dcb": {
        "ratio": 0.5,
        "note": "2:1"
      },
      "hdfc_infinia": {
        "ratio": 0.5,
        "note": "2:1"
      }
    },
    "sweetSpot": {
      "example": "India → Tokyo on ANA Business RT",
      "milesNeeded": 95000,
      "cashValueInr": 285000,
      "cabin": "Business",
      "taxesInr": 18000
    },
    "valuation": {
      "floor": 1.2,
      "realistic": 2.5,
      "ceiling": 3.5
    },
    "deepLink": "https://www.virginatlantic.com/gb/en/flying-club.html",
    "dynamicPricing": false,
    "tags": [
      "ANA access",
      "Phone booking"
    ],
    "lastVerified": "2026-04-08",
    "dataSources": [
      "One Mile at a Time",
      "Frequent Miler"
    ]
  }
];

export const DATA_SOURCES = [
  {
    "id": "pointsmath",
    "name": "PointsMath",
    "type": "blog",
    "url": "https://pointsmath.com",
    "rss": "https://pointsmath.com/feed/",
    "coverage": "Indian bank transfer ratios",
    "trust": "high"
  },
  {
    "id": "livefromalounge",
    "name": "LiveFromALounge",
    "type": "blog",
    "url": "https://livefromalounge.com",
    "rss": "https://livefromalounge.com/feed/",
    "coverage": "Devaluation alerts, card reviews",
    "trust": "high"
  },
  {
    "id": "cardinsider",
    "name": "CardInsider",
    "type": "blog",
    "url": "https://cardinsider.com",
    "rss": "https://cardinsider.com/feed/",
    "coverage": "Card reviews, reward guides",
    "trust": "high"
  },
  {
    "id": "cardexpert",
    "name": "CardExpert",
    "type": "blog",
    "url": "https://cardexpert.in",
    "rss": "https://cardexpert.in/feed/",
    "coverage": "Indian card benefits, co-brand detail",
    "trust": "high"
  },
  {
    "id": "magnify",
    "name": "Magnify.club",
    "type": "blog",
    "url": "https://magnify.club",
    "rss": null,
    "coverage": "Transfer partners, sweet spots",
    "trust": "high"
  },
  {
    "id": "cardmaven",
    "name": "CardMaven",
    "type": "blog",
    "url": "https://cardmaven.in",
    "rss": null,
    "coverage": "SmartBuy strategy, detailed card analyses",
    "trust": "medium"
  },
  {
    "id": "technofino",
    "name": "TechnoFino Forum",
    "type": "forum",
    "url": "https://technofino.in/community",
    "rss": null,
    "coverage": "Real-time community reports, devaluation catches",
    "trust": "high"
  },
  {
    "id": "tapnow",
    "name": "TapNow Community",
    "type": "forum",
    "url": "https://community.tapnow.in",
    "rss": null,
    "coverage": "Transfer bonuses, card tips",
    "trust": "medium"
  },
  {
    "id": "reddit_ccindia",
    "name": "r/CreditCardsIndia",
    "type": "reddit",
    "url": "https://reddit.com/r/CreditCardsIndia",
    "rss": "https://reddit.com/r/CreditCardsIndia/.rss",
    "coverage": "Community devaluation reports, card advice",
    "trust": "medium"
  },
  {
    "id": "points_dojo",
    "name": "Points Dojo",
    "type": "aggregator",
    "url": "https://pointsdojo.com",
    "rss": null,
    "coverage": "Card comparisons, structured rate data",
    "trust": "medium"
  },
  {
    "id": "discord_inpoints",
    "name": "Discord: IN Points",
    "type": "discord",
    "url": null,
    "coverage": "Real-time deal and devaluation alerts",
    "trust": "medium"
  },
  {
    "id": "telegram_ccindia",
    "name": "Telegram: CCIndia",
    "type": "telegram",
    "url": null,
    "coverage": "Community signals, bonus alerts",
    "trust": "medium"
  },
  {
    "id": "awardwallet",
    "name": "AwardWallet Blog",
    "type": "blog",
    "url": "https://awardwallet.com/blog",
    "rss": "https://awardwallet.com/blog/feed/",
    "coverage": "Global program changes",
    "trust": "high"
  },
  {
    "id": "frequent_miler",
    "name": "Frequent Miler",
    "type": "blog",
    "url": "https://frequentmiler.com",
    "rss": "https://frequentmiler.com/feed/",
    "coverage": "RRV methodology, global points strategy",
    "trust": "high"
  },
  {
    "id": "the_points_guy",
    "name": "The Points Guy (TPG)",
    "type": "blog",
    "url": "https://thepointsguy.com",
    "rss": "https://thepointsguy.com/feed/",
    "coverage": "Global valuations benchmark",
    "trust": "high"
  },
  {
    "id": "one_mile_at_a_time",
    "name": "One Mile at a Time",
    "type": "blog",
    "url": "https://onemileatatime.com",
    "rss": "https://onemileatatime.com/feed/",
    "coverage": "Detailed sweet spot analysis",
    "trust": "high"
  },
  {
    "id": "bank_direct",
    "name": "Bank T&C Documents",
    "type": "official",
    "url": null,
    "coverage": "Ground truth for ratios, caps, fees",
    "trust": "highest"
  }
];

export const META = {
  cardCount: 49,
  partnerCount: 38,
  sourceCount: 17
};
